INSERT INTO Usuario (Id_Usuario, Nome, Senha, Tipo_Usuario) VALUES
(1, 'Ana Beatriz Gomes', 'Ana@2024', 'ADMIN'),
(2, 'Carlos Henrique Prado', 'Car$1234', 'ADMIN'),
(3, 'Mariana Lopes Figueiredo', 'Mari!321', 'ADMIN'),
(4, 'João Victor Almeida', 'Joao#999', 'ADMIN'),
(5, 'Larissa Monteiro Rodrigues', 'Lari_22', 'ADMIN'),
(6, 'Pedro Henrique Souza', 'Pedr0@x', 'FUNC'),
(7, 'Lucas Ferreira Martins', 'LFM123', 'FUNC'),
(8, 'Rafael Moraes Carvalho', 'Raf#777', 'ADMIN'),
(9, 'Gabriela Santos Oliveira', 'Gabi!55', 'FUNC'),
(10, 'Ricardo da Silva Nunes', 'Ric@111', 'FUNC'),
(11, 'Viviane Costa Amaral', 'Vivi_012', 'FUNC'),
(12, 'Daniel Oliveira Torres', 'Dan#990', 'FUNC'),
(13, 'Patrícia Nogueira Braga', 'Pat!44', 'FUNC'),
(14, 'Thiago Almeida Souza', 'Thi#555', 'ADMIN'),
(15, 'Fernanda Rocha Braga', 'Frb@12', 'FUNC'),
(16, 'Juliano Ribeiro Costa', 'Jul#098', 'FUNC'),
(17, 'Beatriz Fagundes Paiva', 'Bia@2025', 'FUNC'),
(18, 'Caio André Lima', 'Cai0@66', 'FUNC'),
(19, 'Amanda Torres Vieira', 'Amv#77', 'FUNC'),
(20, 'Diego Barcelos Pinto', 'Dieg0!', 'FUNC'),
(21, 'Alessandra Cunha Ribeiro', 'Acr@xx', 'FUNC'),
(22, 'Vinícius Lopes Machado', 'Vlm321', 'FUNC'),
(23, 'Isabela Correia Prado', 'Isa#2024', 'FUNC'),
(24, 'Marcelo Tavares', 'Mar@000', 'FUNC'),
(25, 'Carolina Figueira', 'Car0@55', 'FUNC'),
(26, 'Otávio Neri', 'Otn!23', 'FUNC'),
(27, 'Renata Bonfim', 'Ren@334', 'FUNC'),
(28, 'Eduardo Ramos', 'Edr#19', 'FUNC'),
(29, 'Larissa Farias', 'Laf@33', 'FUNC'),
(30, 'Hugo Dias', 'Hug0#44', 'ADMIN'),
(31, 'Felipe Duarte', 'Fld@55', 'FUNC'),
(32, 'Jéssica Mendes', 'Jes#88', 'FUNC'),
(33, 'Arthur Freire', 'Art@11', 'FUNC'),
(34, 'Luana Rodrigues', 'Lua!20', 'FUNC'),
(35, 'André Teixeira', 'And#77', 'FUNC'),
(36, 'Camila Rezende', 'Cam@xy', 'FUNC'),
(37, 'Roberto Silva', 'Rob#55', 'FUNC'),
(38, 'Elaine Queiroz', 'Ela@202', 'FUNC'),
(39, 'Gustavo Freitas', 'Gus!999', 'FUNC'),
(40, 'Patrícia Lima', 'Plm@x3', 'ADMIN'),
(41, 'Marcos Pires', 'Marc#44', 'FUNC'),
(42, 'Simone Duarte', 'Sim@22', 'FUNC'),
(43, 'Nathan Silva', 'Nath#76', 'FUNC'),
(44, 'Breno Teixeira', 'Bre@88', 'FUNC'),
(45, 'Elaine Ramos', 'Erm#55', 'FUNC'),
(46, 'Carla Mendonça', 'Car@10', 'FUNC'),
(47, 'Rodrigo Correia', 'Rod#31', 'FUNC'),
(48, 'Luciana Braga', 'Luc@55', 'FUNC'),
(49, 'Henrique Souza', 'Hen#63', 'FUNC'),
(50, 'Marcela Nogueira', 'Mac@99', 'ADMIN'),
(51, 'Samuel Duarte', 'Sam#12', 'FUNC'),
(52, 'Natália Vasconcelos', 'Nat@55', 'FUNC'),
(53, 'Túlio Amaral', 'Tul#10', 'FUNC'),
(54, 'Pâmela Cardoso', 'Pam@44', 'FUNC'),
(55, 'Edgar Rocha', 'Edg#08', 'FUNC'),
(56, 'Talita Cunha', 'Tal@82', 'FUNC'),
(57, 'Ruan Santos', 'Rua#66', 'FUNC'),
(58, 'Bruna Freitas', 'Bru@17', 'FUNC'),
(59, 'Jorge Carvalho', 'Jor#55', 'FUNC'),
(60, 'Caroline Batista', 'Car0#92', 'ADMIN'),
(61, 'Juliana Azevedo', 'Jul@31', 'FUNC'),
(62, 'Leandro Vasques', 'Lea#55', 'FUNC'),
(63, 'Aline Cunha', 'Ali@72', 'FUNC'),
(64, 'Paulo Ramos', 'Pau#88', 'FUNC'),
(65, 'Renan Costa', 'Ren@55', 'FUNC'),
(66, 'Lorena Duarte', 'Lor@90', 'FUNC'),
(67, 'Igor Martins', 'Igo#03', 'FUNC'),
(68, 'Maíra Dias', 'Mai@56', 'FUNC'),
(69, 'Sandro Correia', 'San#91', 'FUNC'),
(70, 'Verônica Medeiros', 'Ver@22', 'ADMIN'),
(71, 'Matheus Prado', 'Mat#63', 'FUNC'),
(72, 'Julio Andrade', 'Jul@55', 'FUNC'),
(73, 'Paula Silveira', 'Pau#02', 'FUNC'),
(74, 'Heloisa Mendes', 'Hel@18', 'FUNC'),
(75, 'Gabriel Sampaio', 'Gab#44', 'FUNC'),
(76, 'Silvia Tavares', 'Sil@77', 'FUNC'),
(77, 'Jonathan Lima', 'Jon#00', 'FUNC'),
(78, 'Lívia Ferreira', 'Liv@88', 'FUNC'),
(79, 'Murilo Monteiro', 'Mur#22', 'FUNC'),
(80, 'Renata Borges', 'Reb@34', 'FUNC');